packages:
  # all packages in direct subdirs of packages/
  # 公用的依赖，比如 http 封装、工具函数
  - 'packages/**'
  # all packages in subdirs of components/
  - 'react/**'
  - 'vue3/**'
  - 'docs/**'
  - 'vue2/**'
  - 'web-components/**'
  - 'tech-talks/**'
  - 'node/**'
  # exclude packages that are inside test directories
  - '!**/test/**'